_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 40
                - 49
                - 51
                - 53
                - 55
                - 89
                - 105
            "2":
                - 1
                - 5
                - 40
                - 49
                - 51
                - 53
                - 55
                - 89
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.9
            "8":
                - 8
            "12": 0.19.9
            "13": linux-x86_64
batch_size:
    value: 128
dataset:
    value: colon
device:
    value: cuda
max_length:
    value: 1800
model_path:
    value: models/best_model
